import axios from "axios";
import Message from "../Models/Message.js";

const OPENAI_URL = "https://api.openai.com/v1/chat/completions";

export const chat = async (req, res) => {
  const rawMessage = req.body?.message;
  const message = rawMessage?.trim();

  if (!message) {
    return res.status(400).json({ error: "Message is required" });
  }

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: "Server configuration missing OPENAI_API_KEY" });
  }

  try {
    const response = await axios.post(
      OPENAI_URL,
      {
        model: "gpt-4o-mini",
        messages: [{ role: "user", content: message }]
      },
      {
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${apiKey}`
        }
      }
    );

    const botReply = response?.data?.choices?.[0]?.message?.content;

    if (!botReply) {
      return res.status(502).json({ error: "No reply generated by AI provider" });
    }

    await Message.create({ userMessage: message, botReply });

    return res.json({ reply: botReply });

  } catch (error) {
    const providerStatus = error?.response?.status;
    const providerMessage =
      error?.response?.data?.error?.message || error?.message || "Error generating response";

    console.error("Chat API error:", {
      providerStatus,
      providerMessage
    });

    if (providerStatus === 401 || providerStatus === 403) {
      return res.status(502).json({ error: "AI provider authentication failed" });
    }

    if (providerStatus === 429) {
      return res.status(502).json({ error: "AI provider rate limit or quota exceeded" });
    }

    return res.status(500).json({ error: providerMessage });
  }
};