import axios from "axios";
import Message from "../Models/Message.js";

const GEMINI_MODEL = process.env.GEMINI_MODEL || "gemini-2.0-flash";
const getGeminiUrl = apiKey =>
  `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(GEMINI_MODEL)}:generateContent?key=${apiKey}`;

export const chat = async (req, res) => {
  const rawMessage = req.body?.message;
  const message = rawMessage?.trim();

  if (!message) {
    return res.status(400).json({ error: "Message is required" });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: "Server configuration missing GEMINI_API_KEY" });
  }

  try {
    const response = await axios.post(
      getGeminiUrl(apiKey),
      {
        contents: [
          {
            role: "user",
            parts: [{ text: message }]
          }
        ],
        generationConfig: {
          temperature: 0.7
        }
      }
    );

    const botReply = response?.data?.candidates?.[0]?.content?.parts
      ?.map(part => part?.text || "")
      .join("\n")
      .trim();

    if (!botReply) {
      return res.status(502).json({ error: "No reply generated by Gemini" });
    }

    await Message.create({ userMessage: message, botReply });

    return res.json({ reply: botReply });

  } catch (error) {
    const providerStatus = error?.response?.status;
    const providerMessage =
      error?.response?.data?.error?.message || error?.message || "Error generating response";

    console.error("Chat API error:", {
      providerStatus,
      providerMessage
    });

    if (providerStatus === 401 || providerStatus === 403) {
      return res.status(502).json({ error: "Gemini API authentication failed" });
    }

    if (providerStatus === 429) {
      return res.status(502).json({ error: "Gemini API rate limit or quota exceeded" });
    }

    return res.status(500).json({ error: providerMessage });
  }
};